### ISSUE TITLE
[Remoto] UX/UI Designer na Influu

### ISSUE THREAD

**Issue by influu** [uxbrasil/vagas#11]
## Descrição da vaga
Estamos em busca de um UX / UI Designer (Remoto) para trabalhar com o design de interfaces WEB e MOBILE.

## Local
Remoto ou Escritório, São Paulo

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Prototipação
- Criação de interface WEB e APP (Android e iOS).
- Criação de Wireframes.
- Ferramentas: Figma, XD, Photoshop, Illustrator e Sketch

**Desejáveis:**
- conhecimentos em HTML
- Criar protótipos funcionais em alta e baixa fidelidade para testes, validações e apresentações para usuários e stakeholders;
- Entendimento sobre usabilidade e acessibilidade.
- Teste de usabilidade com usuário.

## Contratação
PJ a combinar

## Nossa empresa
Somos uma agência com foco no mercado de influenciadores.

## Como se candidatar
Por favor envie um email para contato@influu.me com seu CV ou Link Git- enviar no assunto: [VAGA_UX_UI] + Nome_Sobrenome

## Labels
- PJ
- Pleno
- Remoto
- Sênior

**Comment by kvnol** [comment]
@influu a vaga ainda está aberta?
