### ISSUE TITLE
[Metrô Boa Vista- SP] Designer Júnior/Pleno em BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [uxbrasil/vagas#13]
Descrição da vaga
Estamos em busca de profissionais com experiência em Designer para atuar em projetos para grande cliente. Prazo indeterminado de contratação com muita chance de crescimento. Atividades: concepção de idéias e protótipos de novas features.

Local
Presencial na BRQ- metrô Boa Vista, com idas ao cliente no metrô Conceição- SP.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico 
-previdência privada
-plano odontológico

Requisitos
Experiência com:
- Design Thinking
- Prototipação
- Wireframe
- Metodologias ágeis
- Sketch
- Illustrator
- Invision

Contratação
CLT full pela BRQ.
Horário das 9hs as 18hs, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga Designer.

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com.

Labels
Alocado
CLT
Júnior
Pleno

**Comment by kvnol** [comment]
@ReAnne123 a vaga ainda está aberta?
