### ISSUE TITLE
[Porto Alegre - RS] UX Designer [Triider]

### ISSUE THREAD

**Issue by gregslag** [uxbrasil/vagas#14]
# Sobre nós
O Triider é uma plataforma de serviços. É o app que te conecta aos melhores profissionais do mercado com a mesma praticidade de chamar um carro pelo celular. Nascemos de uma dificuldade que muitas pessoas enfrentam quando precisam contratar profissionais para serviços de manutenção como eletricistas, hidráulicos, pintores, diaristas e outros. Completamos 3 anos de operação em Porto Alegre e iniciamos a nossa expansão nacional em 2019. Já chegamos em Curitiba (PR), Belo Horizonte (MG) e Brasília (DF) e, nos próximos meses, iremos para São Paulo (SP). 
 
Procuramos UX Designer que queira trabalhar em um ambiente inovador e de alta colaboração.
 
Somos apaixonados por usar os melhores métodos e ferramentas para construir os nossos produtos e trazer uma experiência fantástica para os nossos usuários.
 
# Responsabilidades
- Gerenciar e conduzir pesquisa com usuários e stakeholders, testes de usabilidade, benchmarking;
- Conduzir estudos de personas e de comportamento;
- Planejar, executar e consolidar pesquisas qualitativas e quantitativos;
- Compreender necessidades de usuários, motivações e comportamentos, transformando informações em insights e features; 
- Promover continuamente a mudança através de momentos de co-criação, para construção de uma visão estratégica dos produtos por meio da experiência;
- Prototipar e desenvolver interfaces e identidade visual;
 
# Requisitos
- Ter experiência como UX Research;
- Trabalhar dentro do time de UX focado no desenvolvimento do produto;
- Ter experiência na condução de pesquisas de usuário e de produtos;
- Ter experiência em metodologias de design;
- Conhecimento quantitativo, estatístico e de análise de comportamento;
- Ter capacidade investigativa;
- Comunicar efetivamente ideias e conceitos de forma clara, de forma escrita, verbal e visual;
- Conhecer métodos para transmitir ideias e conceitos (storyboards, wireframes, protótipos em papel, etc);
- Ter habilidades em observar padrões de comportamento de pessoas em seus ambientes, identificando suas necessidades e aplicando os resultados destas investigações;
- Domínio de ferramentas de design de interface, como Sketch, XD ou Figma;
 
# Desejável
- Conhecimento da plataforma Figma;
- Conhecimento de metodologias ágeis como design sprint e similares;

# Como se candidatar
Mande seu currículo para para mecontrata@triider.com

**Comment by kvnol** [comment]
@gregslag a vaga ainda está aberta?

**Comment by gregslag** [comment]
Oi @kvnol 
Esta vaga não está mais aberta...
Mas se quiser, você pode enviar o seu currículo para o e-mail mecontrata@triider.com pois logo podemos reabrir esta vaga 😄
