### ISSUE TITLE
Estágio Web Designer_ Rio de Janeiro

### ISSUE THREAD

**Issue by CarolPimentel** [uxbrasil/vagas#15]
## Descrição da vaga
Função: Ajudar equipe na criação de materiais para redes sociais, banners para sites, emails marketing e outras tarefas pontuais.
• Criação de peças para grandes marcas
• Desenvolvimento de Banners e E-mail Marketing;
• Criação de peças para rede social 

** Obrigatórios **
• Cursando ensino superior em Desenho Industrial, Design Gráfico, Comunicação Visual ou afins.
• Domínio de Ferramentas: Photoshop e Illustrator.

Diferenciais:
• Conhecimento em design de interfaces.
• Conhecimento em HTML e CSS3.
- Conhecimento After Effects
- Conhecimento Javascript
- Conhecimento SASS
- Conhecimento Github

• **Possuir portfólio**
-
## Local
 Presencial , Centro - Rio de Janeiro.

## Benefícios
- Vale Refeição
- Vale Transporte

## Contratação
Contrato CIEE Bolsa de R$1250,00

## Nossa empresa
A Fattoria é uma empresa com mais de 15 anos de mercado e um conhecimento sólido do mercado digital. Vamos da criação da marca, planejamento da campanha de marketing digital até o desenvolvimento de um sistema escaláveis e aplicativos mobile. 

## Como se candidatar

Por favor envie um email para rh@fattoriaweb.com.br com o seu CV e portfólios anexados - enviar no assunto: Estágio WDESIGNER

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após a participação nas entrevistas. 
E-mail para contato em caso de não haver resposta: rh@fattoriaweb.com.br

## Labels

-Estágio

**Comment by kvnol** [comment]
Essa vaga não se encaixa como vaga de UX designer, para vagas de front-end, cadastre no https://github.com/frontendbr/vagas/
