### ISSUE TITLE
[SP - Campinas, Barão Geraldo] Analista de UI/UX

### ISSUE THREAD

**Issue by joaoscalett** [uxbrasil/vagas#17]
## Descrição da vaga

Você vai trabalhar diretamente com equipes de desenvolvimento de software em diversos projetos e plataformas. Auxiliará na definição dos produtos, elaboração de ícones, imagens e protótipos. Além disso, você vai analisar, propor melhorias e validar decisões de usabilidade e interface.

## Local

Barão Geraldo, Campinas - SP

## Benefícios

Plano de carreira estruturado e plano de estágio com possibilidade de contratação e benefícios, incluindo Vale-Refeição/Alimentação, Vale Transporte, Gympass e Planos de Saúde e Odontológico

#### Diferenciais

- Horário flexível
- Ambiente informal
- Home office uma vez por semana

## Requisitos

**Obrigatórios:**
- Graduação Superior em Design Gráfico, Publicidade e Propaganda ou semelhante, completa ou em andamento
- Domínio de ferramentas de prototipagem, como Adobe XD, InVision, Sketch ou Figma.
- Portfólio que apresente projetos de design ou materiais de comunicação.

**Desejáveis:**
- Familiaridade com as guidelines do Material Design e iOS.
- Experiência com identidade visual de projetos

**Diferenciais:**
- Conhecimento em HTML, CSS ou programação
- Experiência com metodologias de pesquisa

## Com o quê você vai trabalhar
- Auxiliar na definição dos produtos, buscando sempre se colocar no lugar do usuário
- Elaborar ícones, imagens, componentes, mockups e fluxos de tela
- Montar protótipos de alta fidelidade no Adobe XD
- Fornecer as especificações de design dos produtos para desenvolvedores
- Analisar e apontar melhorias de usabilidade nos nossos produtos
- Validar decisões de usabilidade e interface por meio de testes rápidos
- Auxiliar na definição dos textos necessários às interfaces

## Contratação

CLT ou estágio (30h semanais), conforme disponibilidade 

## Nossa empresa

A EvoluServices é a maior fintech brasileira de meios de pagamento na área da Saúde e está se expandindo para outros segmentos de mercado. Desenvolvemos aplicações web, desktop, embarcadas, iOS e Android nativas.

Trabalhamos em um espaço amplo em Barão Geraldo, na cidade de Campinas - SP, com diversos elementos de descompressão e altamente colaborativo. Recentemente fizemos diversas melhorias e o aumentamos, com o intuito de expandir bastante o time de desenvolvimento.

## Como se candidatar

Envie seu currículo e portfólio para jobs@evoluservices.com, informando a vaga desejada. Para saber mais, acesse https://www.linkedin.com/posts/evoluservices_oportunidadeevoluservices-activity-6620719666153181184-d__Q

## Labels

- Alocado
- CLT
- Estágio
- Júnior

**Comment by kvnol** [comment]
@joaoscalett a vaga ainda está aberta?

**Comment by joaoscalett** [comment]
@kvnol Já foi preenchida, vou fechá-la.
