### ISSUE TITLE
Analista UX/UI - Marketing

### ISSUE THREAD

**Issue by miron15** [uxbrasil/vagas#2]
Local: Limeira/SP
Para se candidatar: juliana.rogatto@kabum.com.br
Sobre o KaBuM:

Somos pioneiros no comércio eletrônico brasileiro, há 16 anos construindo uma história de sucesso e hoje somos o maior e-commerce do segmento de tecnologia na América Latina!

Somos EQUIPE, somos AGILIDADE, somos TODOS NINJAS!

Somos um time diverso, formado por mais de 400 pessoas, obcecados por qualidade, velocidade de entrega e respeito pelo consumidor.

O que você precisa ter:

Experiência do usuário e CRO
Ensino Superior completo em Marketing, Administração de Empresas, Tecnologia ou afins
Atuação prévia em Gestão da área de UX/UI
Conhecer metodologias de design sprint e Agile
Capacidade analítica, e domínio de ferramentas como analytics, excel, datastudio
Experiência em otimizar os resultados de conversão e fidelização

O que buscamos:

Analisar continuamente e diagnosticar a usabilidade, assim como definir as ações de melhoria
Responsável pelo monitoramento e melhoria das jornadas do usuário dentro do nosso e-commerce,
Definir e acompanhar os melhores modelos de interação
Definir estratégia e os objetivos das pesquisas
Identificar oportunidades de agregar valor aos usuários com o maior impacto possível
Trabalhar junto aos times de desenvolvedores e gerentes de produto para priorizar a implementação de oportunidades encontradas
KPIs de conversão, interação e navegação
Trazer insights sobre design e acompanhar os trends globais e boas práticas no desenho de interfaces

**Comment by miron15** [comment]
Para se candidatar enviar CV para Juliana.rogatto@kabum.com.br

**Comment by kvnol** [comment]
@miron15 alocado ou remoto? clt ou pj? junior, pleno ou sênior?

**Comment by kvnol** [comment]
@miron15 a vaga ainda está aberta?

**Comment by miron15** [comment]
Olá TD bem?

Temos 2 novas vagas de UX
Alocado em Limeira - CLT

https://jobs.kenoby.com/kabum

Temos algumas vagas de dev tambem python e fullstack

Em seg, 8 de jun de 2020 20:17, Kevin Oliveira <notifications@github.com>
escreveu:
