### ISSUE TITLE
[São Paulo]  UX Researcher na Platform Builders 

### ISSUE THREAD

**Issue by Ana300** [uxbrasil/vagas#21]
Por aqui, quem se desafia sabe o que é isso. Você será responsável pela prototipação da jornada do usuário, através do contínuo desenvolvimento de todo produto. Já imaginou fazer parte do nosso Movimento e ter chance real de construir sua própria história? Com liberdade e autonomia para inovação e construção, compreendendo a essência da Builders, garantindo uma experiência intuitiva que encante nossos parceiros.
**#SejaBuilder**

**Conhecimentos que vão gerar valor nos projetos:**
Compreender os conceitos de Design Thinking
Dominar técnicas de pesquisa exploratória e pesquisa confirmatória
Dominar conceitos para seleção de amostra
Dominar conceitos quantitativos e qualitativos
Compilação de material criado/levantado

**O que te aproxima de se tornar um(a) Builder:**
Engajamento com nossa cultura, saber se relacionar com nossos mitos e magas, ser resiliente, capacidade de fazer acontecer, determinação.

Local de Trabalho: São Paulo/SP
Remuneração: A definir
Modalidade: PJ

**INFORMAÇÕES ADICIONAIS**
Oportunidades reais de empreender e impactar
Fazer parte de uma comunidade de empreendedores de ponta, o Movimento
Inovação e criação liberados
Participar de um processo único de geração de valor
Contribuir na criação de métodos disruptivos
Colocar suas ideias no mercado, na prática! :)
Possibilidade de Profit share em novos Negócios
Prestador de Serviços (PJ)
Flexibilidade de horário

**Curtiu? Faça sua inscrição por aqui** - https://sejabuilder.gupy.io/jobs/143961

**Comment by kvnol** [comment]
@Ana300  a vaga ainda está aberta?
