### ISSUE TITLE
[Avenida Paulista-São Paulo] UX Sênior em BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [uxbrasil/vagas#23]
Descrição da vaga
Estamos em busca de um profissional com experiência em UX para atuar em grande empresa na Av. Paulista. Prazo indeterminado de contratação com muita chance de crescimento. Atuará com elaboração de mapas de navegação do usuário, testes de usabilidade, criação, desenvolvimento e implementação de soluções inovadoras e atraentes, prototipação, fluxo do usuário e de processos, ligando a interação comunicativa às ideias de Design.

Local
Presencial no cliente na Avenida Paulista- São Paulo (metrô Consolação).

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico
-previdência privada
-plano odontológico

Requisitos:
Ter realizado benchmarks, estudos de aprimoramento, criando padrões de navegabilidade voltados a otimização de performance e engajamento.
Conhecimentos: Illustrator, Photoshop e InDesign, MaterialDesign, Flat Design, Axure, Sketch.

Contratação
CLT full pela BRQ.
Horário das 8h30 as 18hs, de segunda a sexta com 1h30 de almoço.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga UX Sênior- Av. Paulista.

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com.

Labels
Alocado
CLT
Sênior

**Comment by kvnol** [comment]
@ReAnne123 a vaga ainda está aberta?
