### ISSUE TITLE
[remoto] UI/UX Designer na empreender

### ISSUE THREAD

**Issue by andreas-monday** [uxbrasil/vagas#26]
## Descrição da vaga

Se você é um(a) UI/UX Designer com pelo menos 3 anos de experiência em produtos digitais, junte-se a nós.

## Local

Remoto

## Contratação

PJ

## Como se candidatar

Para participar da seleção, acesse o site
https://empreender.hrpartner.io/jobs
Muito obrigado

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by kvnol** [comment]
@andreas-monday a vaga ainda está aberta?
