### ISSUE TITLE
[São Paulo] - Designer UI/UX - Hoobox 

### ISSUE THREAD

**Issue by gusmana** [uxbrasil/vagas#27]
## About us
A HOOBOX  é uma empresa que utiliza Inteligência Artificial e Visão Computacional para criar sistemas incríveis nas áreas da saúde, segurança, transporte e varejo. Com sede no Brasil e nos Estados Unidos, a HOOBOX desenvolve tecnologia de reconhecimento facial de alta precisão, e recentemente, lançou seu primeiro produto na CES 2019, a maior feira de tecnologia do mundo. A HOOBOX acredita na qualidade e no esforço do seu time para construir novas tecnologia e negócios de maneira acelerada.

Na HOOBOX você vai trabalhar com times multidisciplinares. Vai ter o desafio de desenvolver produtos inovadores (tem que gostar de pesquisar) e pode ser que surjam demandas e oportunidades de última hora (nesses momentos você tem que ser proativo e multitasking).

Esperamos que você tenha match com a cultura da empresa!!! 

## REQUISITOS
-Como um bom designer de interfaces, é importante conhecer os princípios da usabilidade (heurísticas e guidelines) e entender o processo de desenvolvimento de um produto digital;
-Experiência com Metodologias Ágeis, Scrum e Design Sprint;
-Experiência com design de interfaces para mobile e softwares;
-Domínio da ferramenta Adobe Creative Suite;
-Boa comunicação para expor suas ideias.

## DIFERENCIAL
-Formação acadêmica em design digital, design gráfico, design de games ou áreas afins;
-Boa relação interpessoal.

## LOCAL
HOOBOX SP / Eretz.bio
Vila Mariana – São Paulo 

**Envie seu CV para team@hoo-box.com com o assunto “Designer UX/UI – Jr”.**

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by kvnol** [comment]
@gusmana a vaga ainda está aberta?

**Comment by gusmana** [comment]
@kvnol Acabamos de contratar, mas pode enviar seu currículo que existe a previsão de surgerem novas vagas.

**Comment by kvnol** [comment]
@gusmana ok, obrigado. estou perguntando apenas para ver se é necessário deixar esse tópico aberto. Estou fechando.
