### ISSUE TITLE
[RJ/Remoto] UX Designer SR na [SOFTTEK]

### ISSUE THREAD

**Issue by renanrufino** [uxbrasil/vagas#30]
**### Local de Trabalho**
Remoto / Praia do Flamengo,200 - Flamengo

**### Empresa**
Fundada em 1982, a Softtek é uma fornecedora global de soluções orientadas a processos de TI. 
No momento, estamos buscando Profissionais com o perfil abaixo:

**### UX Designer SR na Sofftek**

**Atividades Profissionais:**
Colaborar na concepção de produtos junto com product owners, designers e desenvolvedores.
Planejar e realizar pesquisas quanti/quali, entrevistas com usuários, testes de usabilidade, e qualquer outra dinâmica que fizer sentido para o projeto, criar diagramas, fluxos de navegação, user journeys.
Fazer a ponte entre a parte visual e a implementação técnica fornecida pelos desenvolvedores, consumindo serviços e implementando o uso e a geração de dados no Front-End além da comunicação com o Back-End. 
Ser embaixador das boas práticas de usabilidade. 
Experiência na concepção de aplicações, experiências, websites, produtos e serviços que equilibram as necessidades dos usuários, objetivos de negócio e restrições tecnológicas. 
Background em design de interação, experiência do usuário, comunicação visual, ou outras disciplinas relacionadas ao design. 
Familiaridade com padrões de interface de usuário para web e aplicativos móveis. 
Desenvolver boa relação com clientes e ajudá-los a entender e a mapear cenários do produto. 
Ter uma visão ampla sobre os projetos e facilidade de entender o usuário. 
Mapear ou criar e documentar fluxos de navegação. 
Desenvolver protótipos de baixa ou alta fidelidade que sejam estáticos ou navegáveis. 
Documentar e desenvolver processos de design como: mapas de jornada, storyboard, personas, user flow, análise heurística e mapear caso e cenários de uso. 
Principais Ferramentas: Sketch, Photoshop, Illustrator, Invision, Zeplin interface de usuário para web. 
Design aplicações, experiências, websites, produtos e serviços UX/UI designer. 
Autonomia e domínio de técnicas para projetar soluções. 
Capacidade de articular ideias, seja de forma oral ou através de entregáveis (mockups, storyboards, wireframes, jornadas, diagramas, protótipos, layouts, etc). 

**Diferencial:** 
Experiência na Plataforma Mobile 

**Requisitos**
*Experiência:*
- Superior completo em áreas correlatas (Marketing Digital, Marketing, Design de Interação, Design Thinking, Designer gráfico, Comunicação e áreas afins)
- Experiência com prototipagem
- Experiência com testes de usabilidade
- Capacidade de embasar as soluções propostas, levando em conta a necessidades da operação.
- Conhecimento de metodologias ágeis (ex: Scrum, SAFe)
- Familiaridade com metodologias de Design de Serviços, Agile/Lean, Pesquisas com usuários, Design System

**Outras informações: **
Boa comunicação e ter clareza ao apresentar suas ideias. 

**Local de Atuação:** Rio de Janeiro
**Período:** Indeterminado
**Contratação:** CLT
**Oferecemos:** Salário Atrativo + Benefícios 
Maiores detalhes serão passados no momento da entrevista.

**CLT / Salário a combinar.**

Por favor envie um e-mail para renan.souza@softtek.com com seu CV anexado 
- enviar no assunto: Vaga UX SR

## Labels
- Alocado
- CLT
- Remoto
- Sênior

**Comment by kvnol** [comment]
@renanrufino a vaga ainda está aberta?
