### ISSUE TITLE
[São Paulo] Junior UI Designer na Easy Carros

### ISSUE THREAD

**Issue by easycarros-tech** [uxbrasil/vagas#4]
## Sobre a Easy Carros
A Easy Carros é uma empresa que nasceu em 2014, focada no mercado de mobilidade.
Identificamos que hoje, 40% do valor de tudo o que compramos no nosso dia a dia (o pão do café da manhã, o chocolate de sobremesa, a cervejinha do final do dia) é referente ao custo de logística, que é extremamente caro no Brasil.

E o que queremos é criar cada vez mais serviços e tecnologias que possam entregar economia de custos para o setor de logística das principais empresas, para que, assim, os produtos cheguem a um preço muito mais justo e em conta para nós, os consumidores. 
Queremos, então, impactar a vida de milhões de brasileiros através dos nossos produtos. 

Nosso sonho é grande e nossa empresa tem sangue no olho para alcançar esse resultado. Trabalhamos focados em 5 principais valores: Ir além do esperado, Aprendizado exponencial, Ir fundo em dados e tecnologia, Winning Together e Pensamento de dono.

Você tem esses valores? Quer transformar o mundo? Se sim, aqui é o seu lugar.

## O que você precisa saber
* Criação de interfaces visuais, protótipos e style guides usando de melhores práticas e padrões;
* Pesquisas e benchmarkings visuais (UI) de produtos e comportamentos de componentes;
* Conhecimento nas Guidelines e Frameworks de Design
* Responsável por todos os aspectos referentes a UI em Web e Apps;
* Trabalhar com ferramentas como o Sketch, XD, Photoshop, Illustrator, Marvel ou outras ferramentas de Design e prototipagem;
* Conectado com comunidades e tendências de design;
Experiência trabalhando com metodologias ágeis (Scrum e Kanban).

## Competências necessárias

* Solucionador de problemas;
* Com espírito criativo;
* Mindset voltado ao crescimento;
* Forte comunicador;
* Adaptável.

## Contratação
* PJ
* Alocado
* Pinheiros

## Benefícios
* Férias remuneradas
* Auxílio médico pela [Cuidas](https://www.cuidas.com.br)

## Gostou? Candidate-se!
[https://new.easycarros.com/vagas/](https://new.easycarros.com/vagas/)

**Comment by kvnol** [comment]
@easycarros-tech clt ou pj? alocado ou remoto?

**Comment by easycarros-tech** [comment]
> @easycarros-tech clt ou pj? alocado ou remoto?

Atualizei a mensagem!

**Comment by easycarros-tech** [comment]
We're hiring!

**Comment by easycarros-tech** [comment]
Fechamos a vaga, mas você pode continuar de olho nas nossas oportunidades em [https://new.easycarros.com/vagas/](https://new.easycarros.com/vagas/).
