### ISSUE TITLE
[Faria Lima- São Paulo] Analista de Produtos Sênior em BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [uxbrasil/vagas#5]
A BRQ tem paixão por transformar negócios com tecnologia, e há 26 anos apoia a digitalização de bancos, seguradoras, empresas de telecomunicações e outras empresas líderes em seus setores.
Os serviços e soluções oferecidos pela BRQ, aceleram a Transformação Digital em seus clientes e estão estruturados para suportar todo o ciclo de evolução:
- Pensar e Desenhar 
- Aportar tecnologia
- Construir e Evoluir
Unindo o Negócio do Cliente com a Tecnologia Correta e uma nova Cultura que elimina desperdícios, acelera a comunicação e otimiza a produtividade, a BRQ Digital Solutions apoia seus clientes para que seus negócios cresçam exponencialmente.

**Analista de Processos/ Produtos Sênior**
Estamos em busca de um profissional que tenha experiência com Design Thinking, sendo grande diferencial conhecer Blueprint.
Atuará como facilitador em grande banco americano, fazendo a integração entre as áreas de Negócios, TI e Produtos.
Imprescindível inglês avançado/fluente, pois atuará com times internacionais.
Necessário formação superior completa.
Diferenciais: conhecer produtos bancários, Capital Market e Supply Chain.
CLT, salário a combinar + atrativo pacote de benefícios.
Horário comercial.
Local: Faria Lima- São Paulo (presencial).

Aos interessados, enviar o currículo para ryokota@brq.com

**Comment by kvnol** [comment]
@ReAnne123 a vagsa ainda está aberta?
