### ISSUE TITLE
[Curitiba] UX Researcher na [TRACKMOB]

### ISSUE THREAD

**Issue by MicaelaMateos03** [uxbrasil/vagas#8]
## Responsabilidades:

Conduzir pesquisa com dados quantitativos e qualitativos a fim de gerar insumos para as equipes de marketing e produto.
Planejar e marcar entrevistas com potenciais usuários.
Criar escopos de projeto de produto considerando escalabilidade.
Projetar experiências tendo em mente o design centrado na tarefa do usuário
Desenhar, jornadas de usuário, fluxos de tarefa e organogramas para aplicar aos produtos desenvolvidos.
Fazer protótipos de alta fidelidade a fim de facilitar a documentação para desenvolvimento, respeitando princípios de usabilidade.
Redigir documentos acessíveis e compreensíveis para a equipe de desenvolvimento.
Colaborar demonstrando atitude proativa com stakeholders, time de produto, gerente de produto e desenvolvimento para criar a estratégia de ux.

## Local

https://goo.gl/maps/EgmfuW428td7qw8Q6

Av. Cândido de Abreu, 776 - Sala 2102 - Centro Cívico, Curitiba

## Benefícios

- Descanso Remunerado já nos primeiros 6 meses de empresa.
- Day-off de aniversário.
- Plano individual de desenvolvimento, com possíveis cursos, palestras e eventos.
- Acesso à plataformas de estudos a distância.
- Auxílio laptop caso queria usar o seu próprio PC.
- Horário Semi-Flexível
- Licença Paternidade com mais de uma opção de tempo/trabalho
- Realização de sentir que o seu trabalho tem um impacto real em diversas causas sociais.

## Requisitos

**Obrigatórios:**
- Querer mudar o mundo!
- Mínimo de 5 anos de experiência com pesquisa qualitativa com pessoas.
- Capacidade de tornar protótipos de interface em experiências navegáveis em programas de prototipação como Figma, Adobe XD, Sketch.
- Capacidade de observar um sistema e fazer inferências sobre ele com base em pesquisa.
- Familiaridade com métodos do design thinking
- Familiaridade com métodos ágeis, kanban, scrum.
- Leitura em inglês.

**Diferenciais:**
- Pós graduação em design de serviços, ou mestrado em áreas de ciências sociais aplicadas.
- Facilidade de aprender
- Familiaridade com métodos ágeis, kanban, scrum.
- Experiência com produtos para solução de negócios (e-commerce, motor de cobrança)- 
- Ter lançado pelo menos um produto digital do início ao fim
- Habilidade com desenho manual
- Desenhar wireframes
- Desenhar interface gráfica de alta definição
- Fluência em Inglês

## Contratação

PJ a combinar

## Nossa empresa

O Terceiro Setor ainda é ultrapassado quando se trata do uso de tecnologias. As nossas soluções permitem que as ONGs afiem a gestão de doadores e de doações, sua comunicação e também seu marketing. O objetivo é aumentar a aquisição de doadores, melhorar a retenção dessas pessoas e tornar a captação de recursos mais eficaz como um todo. Além disso, buscamos reduzir tempo de trabalho de back office, que seria gasto em atividades como o gerenciamento da base de dados de doadores em planilhas ou na resolução de falhas de cobrança junto ao banco.

A Trackmob oferece soluções tecnológicas desenvolvidas exclusivamente para o Terceiro Setor. Atualmente, disponibilizamos uma suíte de quatro produtos: um CRM para ONGs, uma página de doação online, o Portal do Colaborador (onde doadores acompanham o andamento das causas que apoiam) e o Aplicativo Móvel F2F, que converte uma pessoa interessada em uma nova doadora no local onde ela estiver.

Temos orgulho do nosso trabalho e da missão que temos de **melhorar o mundo e queremos ter você conosco nessa missão!**

## Como se candidatar

Por favor aplique na vaga pelo link 

[https://trackmob.recruiterbox.com/jobs/fk01q9n?source=](https://trackmob.recruiterbox.com/jobs/fk01q9n?source=)

## Labels

- Alocado
- PJ
- Home Office
- Férias

**Comment by kvnol** [comment]
@MicaelaMateos03 a vaga ainda está aberta?
